### ISSUE TITLE
TidyTab dashboard initially opens in default theme even if the night theme is chosen

### ISSUE THREAD

**Issue by erenseymen** [eggplanetio/tidytab#63] opened 2017-04-26 06:55 UTC
To reproduce:
1) TidyTab dashboard is pinned.
2) Night theme is chosen.
3) Close Chrome
4) Open it again
* Dashboard initially opens in default (light) theme. After a little while it changes to night theme. *FAIL*
EXPECTED: It should open in night theme from the start.

Note: This is more obvious when Chrome is opened for the first time or the computer is slow.

Chrome 58.0.3029.81 (64-bit)
TidyTab v2.7.0
Windows 10 Pro

**Comment by briangonzalez** [comment] 2017-04-26 22:21
Thanks for the report! I know what the issue is.

**Comment by briangonzalez** [comment] 2017-05-15 04:45
Fixed in 2.11.0

**Closed by briangonzalez** 2017-05-15 04:45 UTC
Labels: bug
