### ISSUE TITLE
After a window is seperated into 2 windows if you try to tidy the first window, the second window is tidied

### ISSUE THREAD

**Issue by erenseymen** [eggplanetio/tidytab#100] opened 2017-07-10 15:09 UTC
Video: http://jmp.sh/ezeQREi

Steps to reproduce:
1) There are 3 tabs in a window: tabA, tabB, tabC
2) Seperate tabA as another window
3) Go back to the first window
4) Click on TidyTabs and tidy 2 tabs
>> tabB and tabC should be tidied but tabA is tidied. *FAIL*

**Comment by briangonzalez** [comment] 2017-07-10 18:29
Thanks for the report. I think this is a duplicate of #99. Closing for now...

**Closed by briangonzalez** 2017-07-10 18:29 UTC

**Comment by briangonzalez** [comment] 2017-07-12 13:45
Fixed: https://chrome.google.com/webstore/detail/tidytab/lkglfdjcamhjoggmabobhggmpfjhccff?authuser=1

**Comment by erenseymen** [comment] 2017-07-12 14:21
verification passed. thx.
